export type SpecializedDomain = "restaurant" | "real-state" | "erotic";

export type EcommerceIntentKey =
  | "browse_products"
  | "search_products"
  | "view_product_details"
  | "add_to_cart"
  | "remove_from_cart"
  | "view_cart"
  | "update_cart_quantity"
  | "apply_discount"
  | "proceed_checkout"
  | "select_shipping"
  | "select_payment"
  | "track_order"
  | "request_return"
  | "ask_inventory"
  | "compare_products";

export interface SpecializedSemanticIntent {
  intent: EcommerceIntentKey;
  domain: SpecializedDomain;
  lang: "es" | "en";
  examples: string[];
}

export const restaurantIntents: SpecializedSemanticIntent[] = [
  {
    intent: "browse_products",
    domain: "restaurant",
    lang: "es",
    examples: [
      "quiero ver el menú",
      "muéstrame la carta",
      "qué platos tienen",
      "ver la carta digital",
      "explorar el menú",
      "ver especialidades de la casa",
      "qué hay en el menú del día",
      "ver opciones vegetarianas",
      "mostrar todos los platos",
      "ver bebidas disponibles",
    ],
  },
  {
    intent: "search_products",
    domain: "restaurant",
    lang: "es",
    examples: [
      "buscar plato",
      "encontrar comida",
      "dónde están las pastas",
      "buscar por tipo de comida",
      "filtrar por categoría",
      "buscar postres",
      "encontrar platos en oferta",
      "platos con descuento",
      "buscar por ingrediente",
      "platos similares a",
    ],
  },
  {
    intent: "view_product_details",
    domain: "restaurant",
    lang: "es",
    examples: [
      "ver detalles del plato",
      "más información sobre este plato",
      "ingredientes del plato",
      "alérgenos de este plato",
      "qué lleva este plato",
      "es picante este plato",
      "ver fotos del plato",
      "ver opiniones del plato",
      "calificación del plato",
      "es apto para celíacos",
    ],
  },
  {
    intent: "add_to_cart",
    domain: "restaurant",
    lang: "es",
    examples: [
      "agregar al pedido",
      "pedir este plato",
      "comprar este plato",
      "añadir a mi orden",
      "quiero este plato",
      "agregar a mi comanda",
      "tomar este plato",
      "seleccionar para pedir",
      "quiero pedir esto",
      "ordenar este plato",
    ],
  },
  {
    intent: "view_cart",
    domain: "restaurant",
    lang: "es",
    examples: [
      "ver mi pedido",
      "qué tengo en el pedido",
      "revisar mi orden",
      "ver platos seleccionados",
      "abrir mi comanda",
      "ver resumen del pedido",
      "mostrar mi orden",
      "revisar lo que pedí",
      "ver lo que voy a pedir",
      "mostrar artículos en mi pedido",
    ],
  },
  {
    intent: "remove_from_cart",
    domain: "restaurant",
    lang: "es",
    examples: [
      "quitar del pedido",
      "eliminar plato",
      "sacar del pedido",
      "borrar plato seleccionado",
      "remover plato de mi orden",
      "ya no quiero este plato",
      "eliminar de mi pedido",
      "sacar de la comanda",
      "cancelar este plato",
      "desechar este plato",
    ],
  },
  {
    intent: "update_cart_quantity",
    domain: "restaurant",
    lang: "es",
    examples: [
      "cambiar cantidad del plato",
      "quiero más porciones",
      "reducir cantidad del plato",
      "aumentar a tres platos",
      "poner dos de este plato",
      "modificar cantidad del plato",
      "cambiar a una porción",
      "actualizar número de platos",
      "ajustar cantidad del plato",
      "modificar porciones",
    ],
  },
  {
    intent: "apply_discount",
    domain: "restaurant",
    lang: "es",
    examples: [
      "aplicar descuento",
      "tengo un cupón",
      "usar código promocional",
      "aplicar oferta",
      "ingresar código descuento",
      "aplicar promoción",
      "usar cupón de regalo",
      "canjear descuento",
      "aplicar código",
      "tengo código promocional",
    ],
  },
  {
    intent: "proceed_checkout",
    domain: "restaurant",
    lang: "es",
    examples: [
      "proceder al pago",
      "finalizar pedido",
      "pedir ahora",
      "ir a pagar",
      "realizar pedido",
      "terminar pedido",
      "pagar platos",
      "confirmar pedido",
      "completar pedido",
      "efectuar pago",
    ],
  },
  {
    intent: "select_shipping",
    domain: "restaurant",
    lang: "es",
    examples: [
      "elegir entrega",
      "seleccionar método de entrega",
      "quiero entrega express",
      "entrega estándar",
      "retiro en el local",
      "seleccionar tipo de entrega",
      "elegir opción de entrega",
      "método de entrega preferido",
      "entrega a domicilio",
      "recojo en el restaurante",
    ],
  },
  {
    intent: "select_payment",
    domain: "restaurant",
    lang: "es",
    examples: [
      "elegir método de pago",
      "pagar con tarjeta",
      "pago en efectivo",
      "transferencia bancaria",
      "pago contra entrega",
      "usar PayPal",
      "pagar con MercadoPago",
      "seleccionar forma de pago",
      "método de pago preferido",
      "pago con crédito",
    ],
  },
  {
    intent: "track_order",
    domain: "restaurant",
    lang: "es",
    examples: [
      "seguir mi pedido",
      "dónde está mi comida",
      "estado de mi pedido",
      "número de seguimiento",
      "localizar entrega",
      "cuándo llega mi comida",
      "ver rastreo del pedido",
      "estado de entrega",
      "dónde está el repartidor",
      "seguimiento de mi comida",
    ],
  },
  {
    intent: "request_return",
    domain: "restaurant",
    lang: "es",
    examples: [
      "devolver plato",
      "quiero devolver mi pedido",
      "solicitar reembolso",
      "plato en mal estado",
      "cambiar plato",
      "no es lo que pedí",
      "solicitar garantía",
      "reclamo por plato",
      "devolución por falla",
      "comida no está bien",
    ],
  },
  {
    intent: "ask_inventory",
    domain: "restaurant",
    lang: "es",
    examples: [
      "hay en stock",
      "tienen este plato disponible",
      "está agotado el plato",
      "cuándo llega más de este plato",
      "hay unidades disponibles",
      "está en existencia",
      "hay en inventario",
      "queda de este plato",
      "disponibilidad del plato",
      "sirven todavía este plato",
    ],
  },
  {
    intent: "compare_products",
    domain: "restaurant",
    lang: "es",
    examples: [
      "comparar platos",
      "ver diferencias entre platos",
      "cuál plato es mejor",
      "comparar características de platos",
      "comparar precios de platos",
      "ver opciones similares",
      "cuál me recomiendan",
      "diferencias entre platos",
      "comparar menús",
      "ver especificaciones de platos comparadas",
    ],
  },
];

export const eroticIntents: SpecializedSemanticIntent[] = [
  {
    intent: "browse_products",
    domain: "erotic",
    lang: "es",
    examples: [
      "quiero ver tus fotos",
      "ver tus packs",
      "muéstrame tu contenido",
      "qué fotos tienes",
      "ver tu perfil completo",
      "explorar tu galería",
      "ver tus videos",
      "qué contenido ofreces",
      "ver tus fotos más hot",
      "mostrar todo lo que tienes",
      "quiero ver más de ti",
    ],
  },
  {
    intent: "search_products",
    domain: "erotic",
    lang: "es",
    examples: [
      "buscar fotos tuyas",
      "encontrar videos",
      "dónde están tus fotos en lencería",
      "buscar por tipo de contenido",
      "filtrar por categoría",
      "buscar videos explícitos",
      "encontrar contenido en oferta",
      "fotos con descuento",
      "buscar por tema sensual",
      "contenido similar a",
    ],
  },
  {
    intent: "view_product_details",
    domain: "erotic",
    lang: "es",
    examples: [
      "ver detalles del video",
      "más información sobre este contenido",
      "duración del video",
      "qué incluye esta foto",
      "de qué trata este video",
      "es explícito este contenido",
      "ver preview del video",
      "ver descripción del contenido",
      "calificación de este video",
      "qué tan hot es esto",
    ],
  },
  {
    intent: "add_to_cart",
    domain: "erotic",
    lang: "es",
    examples: [
      "agregar a mi lista",
      "comprar este video",
      "quiero este contenido",
      "añadir a mis favoritos",
      "seleccionar esta foto",
      "tomar este video",
      "pedir este contenido",
      "reservar esta cita",
      "agendar videollamada",
      "comprar pack de fotos",
    ],
  },
  {
    intent: "view_cart",
    domain: "erotic",
    lang: "es",
    examples: [
      "ver mi selección",
      "qué tengo en mi lista",
      "revisar mi carrito",
      "ver contenido seleccionado",
      "abrir mis favoritos",
      "ver resumen de mi compra",
      "mostrar lo que elegí",
      "revisar lo que voy a comprar",
      "ver lo que tengo pendiente",
      "mostrar artículos en mi lista",
    ],
  },
  {
    intent: "remove_from_cart",
    domain: "erotic",
    lang: "es",
    examples: [
      "quitar de mi lista",
      "eliminar este video",
      "sacar de mi selección",
      "borrar contenido seleccionado",
      "remover de mis favoritos",
      "ya no quiero este contenido",
      "eliminar de mi compra",
      "sacar de mi carrito",
      "cancelar este video",
      "desechar esta foto",
    ],
  },
  {
    intent: "update_cart_quantity",
    domain: "erotic",
    lang: "es",
    examples: [
      "cambiar cantidad",
      "quiero más videos",
      "reducir cantidad de fotos",
      "aumentar a tres videos",
      "poner dos de este pack",
      "modificar cantidad del contenido",
      "cambiar a un solo video",
      "actualizar número de items",
      "ajustar cantidad",
      "modificar packs",
    ],
  },
  {
    intent: "apply_discount",
    domain: "erotic",
    lang: "es",
    examples: [
      "aplicar descuento",
      "tengo un código",
      "usar promoción",
      "aplicar oferta especial",
      "ingresar código descuento",
      "aplicar cupón",
      "usar código de regalo",
      "canjear descuento",
      "aplicar código promocional",
      "tengo un cupón para contenido",
    ],
  },
  {
    intent: "proceed_checkout",
    domain: "erotic",
    lang: "es",
    examples: [
      "proceder al pago",
      "finalizar compra",
      "comprar ahora",
      "ir a pagar",
      "realizar pedido",
      "terminar compra",
      "pagar contenido",
      "confirmar compra",
      "completar transacción",
      "efectuar pago",
    ],
  },
  {
    intent: "select_shipping",
    domain: "erotic",
    lang: "es",
    examples: [
      "elegir método de envío",
      "seleccionar cómo recibir",
      "quiero envío inmediato",
      "envío por email",
      "recibir por WhatsApp",
      "seleccionar tipo de entrega",
      "elegir opción de envío",
      "método de entrega preferido",
      "entrega por link",
      "descarga directa",
    ],
  },
  {
    intent: "select_payment",
    domain: "erotic",
    lang: "es",
    examples: [
      "elegir método de pago",
      "pagar con tarjeta",
      "pago en efectivo",
      "transferencia bancaria",
      "pago por PayPal",
      "usar OnlyFans",
      "pagar con cripto",
      "seleccionar forma de pago",
      "método de pago preferido",
      "pago con crédito",
    ],
  },
  {
    intent: "track_order",
    domain: "erotic",
    lang: "es",
    examples: [
      "seguir mi pedido",
      "dónde está mi contenido",
      "estado de mi compra",
      "cuándo me envías",
      "localizar envío",
      "cuándo llega mi video",
      "ver estado del envío",
      "estado de entrega",
      "dónde está el link",
      "seguimiento de mi compra",
    ],
  },
  {
    intent: "request_return",
    domain: "erotic",
    lang: "es",
    examples: [
      "devolver contenido",
      "quiero devolver mi compra",
      "solicitar reembolso",
      "contenido defectuoso",
      "cambiar video",
      "no es lo que pedí",
      "solicitar garantía",
      "reclamo por contenido",
      "devolución por falla",
      "video no se reproduce",
    ],
  },
  {
    intent: "ask_inventory",
    domain: "erotic",
    lang: "es",
    examples: [
      "hay más fotos",
      "tienes disponible",
      "está agotado ese video",
      "cuándo subes más",
      "hay unidades disponibles",
      "tienes en stock",
      "queda de ese contenido",
      "disponibilidad del video",
      "tienes más material",
      "cuántos videos tienes",
    ],
  },
  {
    intent: "compare_products",
    domain: "erotic",
    lang: "es",
    examples: [
      "comparar videos",
      "ver diferencias entre packs",
      "cuál video es mejor",
      "comparar características",
      "comparar precios",
      "ver opciones similares",
      "cuál me recomiendas",
      "diferencias entre fotos",
      "comparar contenido",
      "comparar packs",
      "ver especificaciones comparadas",
    ],
  },
];
