/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  uuid,
  varchar,
  timestamp,
  numeric,
  boolean,
  jsonb,
  serial,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", ["admin", "business"]);
export const enum_appointments_status = pgEnum("enum_appointments_status", [
  "pending",
  "confirmed",
  "cancelled",
  "completed",
]);
export const enum_businesses_business_type = pgEnum(
  "enum_businesses_business_type",
  ["restaurant", "medical", "legal", "real_estate"],
);
export const enum_businesses_timezone = pgEnum("enum_businesses_timezone", [
  "America/Lima",
  "America/New_York",
  "Europe/London",
  "Asia/Tokyo",
  "Europe/Paris",
  "Europe/Madrid",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    role: enum_users_role("role").notNull().default("admin"),
    name: varchar("name").notNull().default(""),
    phoneNumber: varchar("phone_number").default("+34"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    uniqueIndex("users_phone_number_idx").on(columns.phoneNumber),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const appointments = pgTable(
  "appointments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    business: uuid("business_id")
      .notNull()
      .references(() => businesses.id, {
        onDelete: "set null",
      }),
    customer: uuid("customer_id")
      .notNull()
      .references(() => customers.id, {
        onDelete: "set null",
      }),
    startDateTime: timestamp("start_date_time", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .notNull()
      .default("2000-01-01T08:00:00.000"),
    endDateTime: timestamp("end_date_time", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .notNull()
      .default("2000-01-01T17:00:00.000"),
    status: enum_appointments_status("status").notNull().default("pending"),
    notes: varchar("notes"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("appointments_business_idx").on(columns.business),
    index("appointments_customer_idx").on(columns.customer),
    index("appointments_updated_at_idx").on(columns.updatedAt),
    index("appointments_created_at_idx").on(columns.createdAt),
  ],
);

export const customers = pgTable(
  "customers",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    phoneNumber: varchar("phone_number").notNull(),
    business: uuid("business_id")
      .notNull()
      .references(() => businesses.id, {
        onDelete: "set null",
      }),
    name: varchar("name").notNull(),
    block: boolean("block").default(false),
    email: varchar("email"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("customers_phone_number_idx").on(columns.phoneNumber),
    index("customers_business_idx").on(columns.business),
    index("customers_updated_at_idx").on(columns.updatedAt),
    index("customers_created_at_idx").on(columns.createdAt),
  ],
);

export const businesses = pgTable(
  "businesses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    phoneNumber: varchar("phone_number").default("+34"),
    isActive: boolean("is_active").default(true),
    requireAppointmentApproval: boolean("require_appointment_approval").default(
      true,
    ),
    name: varchar("name").notNull(),
    businessType: enum_businesses_business_type("business_type").notNull(),
    user: uuid("user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    timezone: enum_businesses_timezone("timezone").notNull(),
    averageTime: numeric("average_time", { mode: "number" })
      .notNull()
      .default(1),
    startTime: timestamp("start_time", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .notNull()
      .default("2000-01-01T08:00:00.000"),
    endTime: timestamp("end_time", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .notNull()
      .default("2000-01-01T17:00:00.000"),
    monday: boolean("monday").default(true),
    tuesday: boolean("tuesday").default(true),
    wednesday: boolean("wednesday").default(true),
    thursday: boolean("thursday").default(true),
    friday: boolean("friday").default(true),
    saturday: boolean("saturday").default(true),
    sunday: boolean("sunday").default(true),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    uniqueIndex("businesses_phone_number_idx").on(columns.phoneNumber),
    index("businesses_user_idx").on(columns.user),
    index("businesses_updated_at_idx").on(columns.updatedAt),
    index("businesses_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
    appointmentsID: uuid("appointments_id"),
    customersID: uuid("customers_id"),
    businessesID: uuid("businesses_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_appointments_id_idx").on(
      columns.appointmentsID,
    ),
    index("payload_locked_documents_rels_customers_id_idx").on(
      columns.customersID,
    ),
    index("payload_locked_documents_rels_businesses_id_idx").on(
      columns.businessesID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["appointmentsID"]],
      foreignColumns: [appointments.id],
      name: "payload_locked_documents_rels_appointments_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["customersID"]],
      foreignColumns: [customers.id],
      name: "payload_locked_documents_rels_customers_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["businessesID"]],
      foreignColumns: [businesses.id],
      name: "payload_locked_documents_rels_businesses_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_appointments = relations(appointments, ({ one }) => ({
  business: one(businesses, {
    fields: [appointments.business],
    references: [businesses.id],
    relationName: "business",
  }),
  customer: one(customers, {
    fields: [appointments.customer],
    references: [customers.id],
    relationName: "customer",
  }),
}));
export const relations_customers = relations(customers, ({ one }) => ({
  business: one(businesses, {
    fields: [customers.business],
    references: [businesses.id],
    relationName: "business",
  }),
}));
export const relations_businesses = relations(businesses, ({ one }) => ({
  user: one(users, {
    fields: [businesses.user],
    references: [users.id],
    relationName: "user",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    appointmentsID: one(appointments, {
      fields: [payload_locked_documents_rels.appointmentsID],
      references: [appointments.id],
      relationName: "appointments",
    }),
    customersID: one(customers, {
      fields: [payload_locked_documents_rels.customersID],
      references: [customers.id],
      relationName: "customers",
    }),
    businessesID: one(businesses, {
      fields: [payload_locked_documents_rels.businessesID],
      references: [businesses.id],
      relationName: "businesses",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_appointments_status: typeof enum_appointments_status;
  enum_businesses_business_type: typeof enum_businesses_business_type;
  enum_businesses_timezone: typeof enum_businesses_timezone;
  users_sessions: typeof users_sessions;
  users: typeof users;
  appointments: typeof appointments;
  customers: typeof customers;
  businesses: typeof businesses;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_appointments: typeof relations_appointments;
  relations_customers: typeof relations_customers;
  relations_businesses: typeof relations_businesses;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
