/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:db-schema` to regenerate this file.
 */

import type {} from "@payloadcms/db-postgres";
import {
  pgTable,
  index,
  uniqueIndex,
  foreignKey,
  integer,
  uuid,
  varchar,
  timestamp,
  numeric,
  boolean,
  jsonb,
  serial,
  pgEnum,
} from "@payloadcms/db-postgres/drizzle/pg-core";
import { sql, relations } from "@payloadcms/db-postgres/drizzle";
export const enum_users_role = pgEnum("enum_users_role", ["admin", "business"]);
export const enum_appointments_status = pgEnum("enum_appointments_status", [
  "pending",
  "confirmed",
  "cancelled",
  "completed",
]);
export const enum_businesses_general_business_type = pgEnum(
  "enum_businesses_general_business_type",
  ["restaurant", "medical", "legal", "real_estate"],
);
export const enum_businesses_general_timezone = pgEnum(
  "enum_businesses_general_timezone",
  [
    "Europe/Madrid",
    "Europe/Paris",
    "Europe/London",
    "America/Lima",
    "America/New_York",
    "Asia/Tokyo",
  ],
);
export const enum_businesses_country = pgEnum("enum_businesses_country", [
  "ES",
  "COL",
  "MEX",
  "PE",
  "EC",
  "US",
  "CA",
]);
export const enum_businesses_currency = pgEnum("enum_businesses_currency", [
  "USD",
  "MXN",
  "PEN",
  "EUR",
  "GBP",
]);

export const users_sessions = pgTable(
  "users_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("users_sessions_order_idx").on(columns._order),
    index("users_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [users.id],
      name: "users_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const users = pgTable(
  "users",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    role: enum_users_role("role").notNull().default("business"),
    name: varchar("name").notNull().default(""),
    phoneNumber: varchar("phone_number").default("+34"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    uniqueIndex("users_phone_number_idx").on(columns.phoneNumber),
    index("users_updated_at_idx").on(columns.updatedAt),
    index("users_created_at_idx").on(columns.createdAt),
    uniqueIndex("users_email_idx").on(columns.email),
  ],
);

export const third_party_access_sessions = pgTable(
  "third_party_access_sessions",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    expiresAt: timestamp("expires_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("third_party_access_sessions_order_idx").on(columns._order),
    index("third_party_access_sessions_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [third_party_access.id],
      name: "third_party_access_sessions_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const third_party_access = pgTable(
  "third_party_access",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    enableAPIKey: boolean("enable_a_p_i_key"),
    apiKey: varchar("api_key"),
    apiKeyIndex: varchar("api_key_index"),
    email: varchar("email").notNull(),
    resetPasswordToken: varchar("reset_password_token"),
    resetPasswordExpiration: timestamp("reset_password_expiration", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    salt: varchar("salt"),
    hash: varchar("hash"),
    loginAttempts: numeric("login_attempts", { mode: "number" }).default(0),
    lockUntil: timestamp("lock_until", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
  },
  (columns) => [
    index("third_party_access_updated_at_idx").on(columns.updatedAt),
    index("third_party_access_created_at_idx").on(columns.createdAt),
    uniqueIndex("third_party_access_email_idx").on(columns.email),
  ],
);

export const appointments = pgTable(
  "appointments",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    business: uuid("business_id")
      .notNull()
      .references(() => businesses.id, {
        onDelete: "set null",
      }),
    customer: uuid("customer_id")
      .notNull()
      .references(() => customers.id, {
        onDelete: "set null",
      }),
    customerName: varchar("customer_name"),
    timezone: varchar("timezone").notNull(),
    startDateTime: timestamp("start_date_time", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endDateTime: timestamp("end_date_time", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }),
    status: enum_appointments_status("status").notNull().default("pending"),
    numberOfPeople: numeric("number_of_people", { mode: "number" }).default(1),
    notes: varchar("notes"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("appointments_business_idx").on(columns.business),
    index("appointments_customer_idx").on(columns.customer),
    index("appointments_start_date_time_idx").on(columns.startDateTime),
    index("appointments_end_date_time_idx").on(columns.endDateTime),
    index("appointments_updated_at_idx").on(columns.updatedAt),
    index("appointments_created_at_idx").on(columns.createdAt),
  ],
);

export const customers = pgTable(
  "customers",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    phoneNumber: varchar("phone_number").notNull().default("+34"),
    business: uuid("business_id")
      .notNull()
      .references(() => businesses.id, {
        onDelete: "set null",
      }),
    name: varchar("name").notNull(),
    block: boolean("block").default(false),
    email: varchar("email"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("customers_phone_number_idx").on(columns.phoneNumber),
    index("customers_business_idx").on(columns.business),
    index("customers_updated_at_idx").on(columns.updatedAt),
    index("customers_created_at_idx").on(columns.createdAt),
  ],
);

export const businesses_general_next_holiday = pgTable(
  "businesses_general_next_holiday",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    startDate: timestamp("start_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
    endDate: timestamp("end_date", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    }).notNull(),
  },
  (columns) => [
    index("businesses_general_next_holiday_order_idx").on(columns._order),
    index("businesses_general_next_holiday_parent_id_idx").on(
      columns._parentID,
    ),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [businesses.id],
      name: "businesses_general_next_holiday_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const businesses_schedule_monday = pgTable(
  "businesses_schedule_monday",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    open: numeric("open", { mode: "number" }).notNull(),
    close: numeric("close", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("businesses_schedule_monday_order_idx").on(columns._order),
    index("businesses_schedule_monday_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [businesses.id],
      name: "businesses_schedule_monday_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const businesses_schedule_tuesday = pgTable(
  "businesses_schedule_tuesday",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    open: numeric("open", { mode: "number" }).notNull(),
    close: numeric("close", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("businesses_schedule_tuesday_order_idx").on(columns._order),
    index("businesses_schedule_tuesday_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [businesses.id],
      name: "businesses_schedule_tuesday_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const businesses_schedule_wednesday = pgTable(
  "businesses_schedule_wednesday",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    open: numeric("open", { mode: "number" }).notNull(),
    close: numeric("close", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("businesses_schedule_wednesday_order_idx").on(columns._order),
    index("businesses_schedule_wednesday_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [businesses.id],
      name: "businesses_schedule_wednesday_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const businesses_schedule_thursday = pgTable(
  "businesses_schedule_thursday",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    open: numeric("open", { mode: "number" }).notNull(),
    close: numeric("close", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("businesses_schedule_thursday_order_idx").on(columns._order),
    index("businesses_schedule_thursday_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [businesses.id],
      name: "businesses_schedule_thursday_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const businesses_schedule_friday = pgTable(
  "businesses_schedule_friday",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    open: numeric("open", { mode: "number" }).notNull(),
    close: numeric("close", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("businesses_schedule_friday_order_idx").on(columns._order),
    index("businesses_schedule_friday_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [businesses.id],
      name: "businesses_schedule_friday_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const businesses_schedule_saturday = pgTable(
  "businesses_schedule_saturday",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    open: numeric("open", { mode: "number" }).notNull(),
    close: numeric("close", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("businesses_schedule_saturday_order_idx").on(columns._order),
    index("businesses_schedule_saturday_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [businesses.id],
      name: "businesses_schedule_saturday_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const businesses_schedule_sunday = pgTable(
  "businesses_schedule_sunday",
  {
    _order: integer("_order").notNull(),
    _parentID: uuid("_parent_id").notNull(),
    id: varchar("id").primaryKey(),
    open: numeric("open", { mode: "number" }).notNull(),
    close: numeric("close", { mode: "number" }).notNull(),
  },
  (columns) => [
    index("businesses_schedule_sunday_order_idx").on(columns._order),
    index("businesses_schedule_sunday_parent_id_idx").on(columns._parentID),
    foreignKey({
      columns: [columns["_parentID"]],
      foreignColumns: [businesses.id],
      name: "businesses_schedule_sunday_parent_id_fk",
    }).onDelete("cascade"),
  ],
);

export const businesses = pgTable(
  "businesses",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name").notNull(),
    assistantName: varchar("assistant_name").notNull(),
    general_phoneNumber: varchar("general_phone_number").default("+34"),
    general_requireAppointmentApproval: boolean(
      "general_require_appointment_approval",
    ).default(true),
    general_businessType: enum_businesses_general_business_type(
      "general_business_type",
    )
      .notNull()
      .default("restaurant"),
    general_maxCapacity: numeric("general_max_capacity", {
      mode: "number",
    }).default(10),
    general_description: varchar("general_description"),
    general_user: uuid("general_user_id")
      .notNull()
      .references(() => users.id, {
        onDelete: "set null",
      }),
    general_timezone: enum_businesses_general_timezone("general_timezone")
      .notNull()
      .default("Europe/Madrid"),
    general_isActive: boolean("general_is_active").default(true),
    schedule_averageTime: numeric("schedule_average_time", { mode: "number" })
      .notNull()
      .default(60),
    country: enum_businesses_country("country"),
    taxes: numeric("taxes", { mode: "number" }),
    currency: enum_businesses_currency("currency"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("businesses_general_general_user_idx").on(columns.general_user),
    index("businesses_updated_at_idx").on(columns.updatedAt),
    index("businesses_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_kv = pgTable(
  "payload_kv",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key").notNull(),
    data: jsonb("data").notNull(),
  },
  (columns) => [uniqueIndex("payload_kv_key_idx").on(columns.key)],
);

export const payload_locked_documents = pgTable(
  "payload_locked_documents",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    globalSlug: varchar("global_slug"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_locked_documents_global_slug_idx").on(columns.globalSlug),
    index("payload_locked_documents_updated_at_idx").on(columns.updatedAt),
    index("payload_locked_documents_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_locked_documents_rels = pgTable(
  "payload_locked_documents_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
    "third-party-accessID": uuid("third_party_access_id"),
    appointmentsID: uuid("appointments_id"),
    customersID: uuid("customers_id"),
    businessesID: uuid("businesses_id"),
  },
  (columns) => [
    index("payload_locked_documents_rels_order_idx").on(columns.order),
    index("payload_locked_documents_rels_parent_idx").on(columns.parent),
    index("payload_locked_documents_rels_path_idx").on(columns.path),
    index("payload_locked_documents_rels_users_id_idx").on(columns.usersID),
    index("payload_locked_documents_rels_third_party_access_id_idx").on(
      columns["third-party-accessID"],
    ),
    index("payload_locked_documents_rels_appointments_id_idx").on(
      columns.appointmentsID,
    ),
    index("payload_locked_documents_rels_customers_id_idx").on(
      columns.customersID,
    ),
    index("payload_locked_documents_rels_businesses_id_idx").on(
      columns.businessesID,
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_locked_documents.id],
      name: "payload_locked_documents_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_locked_documents_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["third-party-accessID"]],
      foreignColumns: [third_party_access.id],
      name: "payload_locked_documents_rels_third_party_access_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["appointmentsID"]],
      foreignColumns: [appointments.id],
      name: "payload_locked_documents_rels_appointments_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["customersID"]],
      foreignColumns: [customers.id],
      name: "payload_locked_documents_rels_customers_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["businessesID"]],
      foreignColumns: [businesses.id],
      name: "payload_locked_documents_rels_businesses_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_preferences = pgTable(
  "payload_preferences",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    key: varchar("key"),
    value: jsonb("value"),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_preferences_key_idx").on(columns.key),
    index("payload_preferences_updated_at_idx").on(columns.updatedAt),
    index("payload_preferences_created_at_idx").on(columns.createdAt),
  ],
);

export const payload_preferences_rels = pgTable(
  "payload_preferences_rels",
  {
    id: serial("id").primaryKey(),
    order: integer("order"),
    parent: uuid("parent_id").notNull(),
    path: varchar("path").notNull(),
    usersID: uuid("users_id"),
    "third-party-accessID": uuid("third_party_access_id"),
  },
  (columns) => [
    index("payload_preferences_rels_order_idx").on(columns.order),
    index("payload_preferences_rels_parent_idx").on(columns.parent),
    index("payload_preferences_rels_path_idx").on(columns.path),
    index("payload_preferences_rels_users_id_idx").on(columns.usersID),
    index("payload_preferences_rels_third_party_access_id_idx").on(
      columns["third-party-accessID"],
    ),
    foreignKey({
      columns: [columns["parent"]],
      foreignColumns: [payload_preferences.id],
      name: "payload_preferences_rels_parent_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["usersID"]],
      foreignColumns: [users.id],
      name: "payload_preferences_rels_users_fk",
    }).onDelete("cascade"),
    foreignKey({
      columns: [columns["third-party-accessID"]],
      foreignColumns: [third_party_access.id],
      name: "payload_preferences_rels_third_party_access_fk",
    }).onDelete("cascade"),
  ],
);

export const payload_migrations = pgTable(
  "payload_migrations",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    name: varchar("name"),
    batch: numeric("batch", { mode: "number" }),
    updatedAt: timestamp("updated_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
    createdAt: timestamp("created_at", {
      mode: "string",
      withTimezone: true,
      precision: 3,
    })
      .defaultNow()
      .notNull(),
  },
  (columns) => [
    index("payload_migrations_updated_at_idx").on(columns.updatedAt),
    index("payload_migrations_created_at_idx").on(columns.createdAt),
  ],
);

export const relations_users_sessions = relations(
  users_sessions,
  ({ one }) => ({
    _parentID: one(users, {
      fields: [users_sessions._parentID],
      references: [users.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_users = relations(users, ({ many }) => ({
  sessions: many(users_sessions, {
    relationName: "sessions",
  }),
}));
export const relations_third_party_access_sessions = relations(
  third_party_access_sessions,
  ({ one }) => ({
    _parentID: one(third_party_access, {
      fields: [third_party_access_sessions._parentID],
      references: [third_party_access.id],
      relationName: "sessions",
    }),
  }),
);
export const relations_third_party_access = relations(
  third_party_access,
  ({ many }) => ({
    sessions: many(third_party_access_sessions, {
      relationName: "sessions",
    }),
  }),
);
export const relations_appointments = relations(appointments, ({ one }) => ({
  business: one(businesses, {
    fields: [appointments.business],
    references: [businesses.id],
    relationName: "business",
  }),
  customer: one(customers, {
    fields: [appointments.customer],
    references: [customers.id],
    relationName: "customer",
  }),
}));
export const relations_customers = relations(customers, ({ one }) => ({
  business: one(businesses, {
    fields: [customers.business],
    references: [businesses.id],
    relationName: "business",
  }),
}));
export const relations_businesses_general_next_holiday = relations(
  businesses_general_next_holiday,
  ({ one }) => ({
    _parentID: one(businesses, {
      fields: [businesses_general_next_holiday._parentID],
      references: [businesses.id],
      relationName: "general_nextHoliday",
    }),
  }),
);
export const relations_businesses_schedule_monday = relations(
  businesses_schedule_monday,
  ({ one }) => ({
    _parentID: one(businesses, {
      fields: [businesses_schedule_monday._parentID],
      references: [businesses.id],
      relationName: "schedule_monday",
    }),
  }),
);
export const relations_businesses_schedule_tuesday = relations(
  businesses_schedule_tuesday,
  ({ one }) => ({
    _parentID: one(businesses, {
      fields: [businesses_schedule_tuesday._parentID],
      references: [businesses.id],
      relationName: "schedule_tuesday",
    }),
  }),
);
export const relations_businesses_schedule_wednesday = relations(
  businesses_schedule_wednesday,
  ({ one }) => ({
    _parentID: one(businesses, {
      fields: [businesses_schedule_wednesday._parentID],
      references: [businesses.id],
      relationName: "schedule_wednesday",
    }),
  }),
);
export const relations_businesses_schedule_thursday = relations(
  businesses_schedule_thursday,
  ({ one }) => ({
    _parentID: one(businesses, {
      fields: [businesses_schedule_thursday._parentID],
      references: [businesses.id],
      relationName: "schedule_thursday",
    }),
  }),
);
export const relations_businesses_schedule_friday = relations(
  businesses_schedule_friday,
  ({ one }) => ({
    _parentID: one(businesses, {
      fields: [businesses_schedule_friday._parentID],
      references: [businesses.id],
      relationName: "schedule_friday",
    }),
  }),
);
export const relations_businesses_schedule_saturday = relations(
  businesses_schedule_saturday,
  ({ one }) => ({
    _parentID: one(businesses, {
      fields: [businesses_schedule_saturday._parentID],
      references: [businesses.id],
      relationName: "schedule_saturday",
    }),
  }),
);
export const relations_businesses_schedule_sunday = relations(
  businesses_schedule_sunday,
  ({ one }) => ({
    _parentID: one(businesses, {
      fields: [businesses_schedule_sunday._parentID],
      references: [businesses.id],
      relationName: "schedule_sunday",
    }),
  }),
);
export const relations_businesses = relations(businesses, ({ one, many }) => ({
  general_user: one(users, {
    fields: [businesses.general_user],
    references: [users.id],
    relationName: "general_user",
  }),
  general_nextHoliday: many(businesses_general_next_holiday, {
    relationName: "general_nextHoliday",
  }),
  schedule_monday: many(businesses_schedule_monday, {
    relationName: "schedule_monday",
  }),
  schedule_tuesday: many(businesses_schedule_tuesday, {
    relationName: "schedule_tuesday",
  }),
  schedule_wednesday: many(businesses_schedule_wednesday, {
    relationName: "schedule_wednesday",
  }),
  schedule_thursday: many(businesses_schedule_thursday, {
    relationName: "schedule_thursday",
  }),
  schedule_friday: many(businesses_schedule_friday, {
    relationName: "schedule_friday",
  }),
  schedule_saturday: many(businesses_schedule_saturday, {
    relationName: "schedule_saturday",
  }),
  schedule_sunday: many(businesses_schedule_sunday, {
    relationName: "schedule_sunday",
  }),
}));
export const relations_payload_kv = relations(payload_kv, () => ({}));
export const relations_payload_locked_documents_rels = relations(
  payload_locked_documents_rels,
  ({ one }) => ({
    parent: one(payload_locked_documents, {
      fields: [payload_locked_documents_rels.parent],
      references: [payload_locked_documents.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_locked_documents_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    "third-party-accessID": one(third_party_access, {
      fields: [payload_locked_documents_rels["third-party-accessID"]],
      references: [third_party_access.id],
      relationName: "third-party-access",
    }),
    appointmentsID: one(appointments, {
      fields: [payload_locked_documents_rels.appointmentsID],
      references: [appointments.id],
      relationName: "appointments",
    }),
    customersID: one(customers, {
      fields: [payload_locked_documents_rels.customersID],
      references: [customers.id],
      relationName: "customers",
    }),
    businessesID: one(businesses, {
      fields: [payload_locked_documents_rels.businessesID],
      references: [businesses.id],
      relationName: "businesses",
    }),
  }),
);
export const relations_payload_locked_documents = relations(
  payload_locked_documents,
  ({ many }) => ({
    _rels: many(payload_locked_documents_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_preferences_rels = relations(
  payload_preferences_rels,
  ({ one }) => ({
    parent: one(payload_preferences, {
      fields: [payload_preferences_rels.parent],
      references: [payload_preferences.id],
      relationName: "_rels",
    }),
    usersID: one(users, {
      fields: [payload_preferences_rels.usersID],
      references: [users.id],
      relationName: "users",
    }),
    "third-party-accessID": one(third_party_access, {
      fields: [payload_preferences_rels["third-party-accessID"]],
      references: [third_party_access.id],
      relationName: "third-party-access",
    }),
  }),
);
export const relations_payload_preferences = relations(
  payload_preferences,
  ({ many }) => ({
    _rels: many(payload_preferences_rels, {
      relationName: "_rels",
    }),
  }),
);
export const relations_payload_migrations = relations(
  payload_migrations,
  () => ({}),
);

type DatabaseSchema = {
  enum_users_role: typeof enum_users_role;
  enum_appointments_status: typeof enum_appointments_status;
  enum_businesses_general_business_type: typeof enum_businesses_general_business_type;
  enum_businesses_general_timezone: typeof enum_businesses_general_timezone;
  enum_businesses_country: typeof enum_businesses_country;
  enum_businesses_currency: typeof enum_businesses_currency;
  users_sessions: typeof users_sessions;
  users: typeof users;
  third_party_access_sessions: typeof third_party_access_sessions;
  third_party_access: typeof third_party_access;
  appointments: typeof appointments;
  customers: typeof customers;
  businesses_general_next_holiday: typeof businesses_general_next_holiday;
  businesses_schedule_monday: typeof businesses_schedule_monday;
  businesses_schedule_tuesday: typeof businesses_schedule_tuesday;
  businesses_schedule_wednesday: typeof businesses_schedule_wednesday;
  businesses_schedule_thursday: typeof businesses_schedule_thursday;
  businesses_schedule_friday: typeof businesses_schedule_friday;
  businesses_schedule_saturday: typeof businesses_schedule_saturday;
  businesses_schedule_sunday: typeof businesses_schedule_sunday;
  businesses: typeof businesses;
  payload_kv: typeof payload_kv;
  payload_locked_documents: typeof payload_locked_documents;
  payload_locked_documents_rels: typeof payload_locked_documents_rels;
  payload_preferences: typeof payload_preferences;
  payload_preferences_rels: typeof payload_preferences_rels;
  payload_migrations: typeof payload_migrations;
  relations_users_sessions: typeof relations_users_sessions;
  relations_users: typeof relations_users;
  relations_third_party_access_sessions: typeof relations_third_party_access_sessions;
  relations_third_party_access: typeof relations_third_party_access;
  relations_appointments: typeof relations_appointments;
  relations_customers: typeof relations_customers;
  relations_businesses_general_next_holiday: typeof relations_businesses_general_next_holiday;
  relations_businesses_schedule_monday: typeof relations_businesses_schedule_monday;
  relations_businesses_schedule_tuesday: typeof relations_businesses_schedule_tuesday;
  relations_businesses_schedule_wednesday: typeof relations_businesses_schedule_wednesday;
  relations_businesses_schedule_thursday: typeof relations_businesses_schedule_thursday;
  relations_businesses_schedule_friday: typeof relations_businesses_schedule_friday;
  relations_businesses_schedule_saturday: typeof relations_businesses_schedule_saturday;
  relations_businesses_schedule_sunday: typeof relations_businesses_schedule_sunday;
  relations_businesses: typeof relations_businesses;
  relations_payload_kv: typeof relations_payload_kv;
  relations_payload_locked_documents_rels: typeof relations_payload_locked_documents_rels;
  relations_payload_locked_documents: typeof relations_payload_locked_documents;
  relations_payload_preferences_rels: typeof relations_payload_preferences_rels;
  relations_payload_preferences: typeof relations_payload_preferences;
  relations_payload_migrations: typeof relations_payload_migrations;
};

declare module "@payloadcms/db-postgres" {
  export interface GeneratedDatabaseSchema {
    schema: DatabaseSchema;
  }
}
