import { EroticIntentKey, IntentExample } from "./intent.types";

export const erotic: IntentExample<EroticIntentKey>[] = [
  {
    intentKey: "erotic:view_content",
    module: "products",
    domain: "erotic",
    lang: "es",
    requiresConfirmation: "maybe",
    examples: [
      "quiero ver tu galería completa",
      "muéstrame tus fotos disponibles",
      "quiero ver más contenido",
      "puedo ver tus videos",
      "enséñame lo que tienes",
      "quiero explorar tu perfil",
      "ver contenido premium ahora",
      "qué material tienes publicado",
      "quiero ver tus packs",
      "déjame ver tu catálogo",
      "quiero ver tus publicaciones",
      "muestra tu contenido exclusivo",
      "quiero revisar tu galería",
      "ver tus fotos recientes",
      "quiero mirar tu contenido",
      "qué contenido puedo ver",
      "enséñame tu material disponible",
      "quiero ver lo que ofreces",
      "ver tus videos disponibles",
      "puedo revisar tu contenido",
    ],
  },
  {
    intentKey: "erotic:purchase_content",
    module: "products",
    domain: "erotic",
    lang: "es",
    requiresConfirmation: "maybe",
    examples: [
      "quiero comprar este pack",
      "cómo puedo comprar contenido",
      "quiero adquirir este video",
      "me interesa comprar ahora",
      "quiero comprar tus fotos",
      "dónde compro ese pack",
      "quiero pagar por contenido",
      "cómo hago la compra",
      "quiero comprar este contenido",
      "quiero adquirir un pack",
      "quiero comprar acceso completo",
      "me gustaría comprar videos",
      "quiero comprar algo tuyo",
      "cómo se paga esto",
      "quiero comprar ahora mismo",
      "quiero ese pack premium",
      "quiero comprar tu material",
      "puedo comprar ese contenido",
      "quiero adquirir acceso premium",
      "cómo compro tus packs",
    ],
  },
  {
    intentKey: "erotic:ask_services",
    module: "products",
    domain: "erotic",
    lang: "es",
    requiresConfirmation: "maybe",
    examples: [
      "ofreces contenido personalizado",
      "haces videollamadas privadas",
      "qué servicios tienes disponibles",
      "cuáles son tus tarifas",
      "tienes promociones activas",
      "qué modalidades manejas",
      "ofreces packs especiales",
      "cuánto cuesta una sesión",
      "tienes contenido a pedido",
      "cómo funcionan tus servicios",
      "qué opciones ofreces",
      "haces contenido por encargo",
      "tienes horarios disponibles",
      "ofreces sesiones privadas",
      "qué incluye cada pack",
      "hay descuentos disponibles",
      "puedo pedir contenido personalizado",
      "qué tipo de contenido haces",
      "cómo agendo una sesión",
      "qué planes tienes disponibles",
    ],
  },
] as const;
